// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGylYEVfq4Mbpyra7A6uCpeZMk7v7uBvM',
    appId: '1:462932257595:web:6d6153921cafd6f4afe51e',
    messagingSenderId: '462932257595',
    projectId: 'hospynav-b6fae',
    authDomain: 'hospynav-b6fae.firebaseapp.com',
    storageBucket: 'hospynav-b6fae.firebasestorage.app',
    measurementId: 'G-81CWLNXSLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvt3MVgES4M8GRXsVZHSckNBYHVp2wLN4',
    appId: '1:462932257595:android:7ac9b05e513817ebafe51e',
    messagingSenderId: '462932257595',
    projectId: 'hospynav-b6fae',
    storageBucket: 'hospynav-b6fae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUI9LXs9aSNvBmV8EitHRYNqhzcXJBYG4',
    appId: '1:462932257595:ios:21cab9768d5aa734afe51e',
    messagingSenderId: '462932257595',
    projectId: 'hospynav-b6fae',
    storageBucket: 'hospynav-b6fae.firebasestorage.app',
    androidClientId: '462932257595-qa4itaneurbb6ljrkov6gvl7qvbivefp.apps.googleusercontent.com',
    iosClientId: '462932257595-0pbur5jsn8dlq4adempgljtalgqat92k.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospyNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUI9LXs9aSNvBmV8EitHRYNqhzcXJBYG4',
    appId: '1:462932257595:ios:21cab9768d5aa734afe51e',
    messagingSenderId: '462932257595',
    projectId: 'hospynav-b6fae',
    storageBucket: 'hospynav-b6fae.firebasestorage.app',
    androidClientId: '462932257595-qa4itaneurbb6ljrkov6gvl7qvbivefp.apps.googleusercontent.com',
    iosClientId: '462932257595-0pbur5jsn8dlq4adempgljtalgqat92k.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospyNav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGylYEVfq4Mbpyra7A6uCpeZMk7v7uBvM',
    appId: '1:462932257595:web:f9accddff7439ae7afe51e',
    messagingSenderId: '462932257595',
    projectId: 'hospynav-b6fae',
    authDomain: 'hospynav-b6fae.firebaseapp.com',
    storageBucket: 'hospynav-b6fae.firebasestorage.app',
    measurementId: 'G-XVTZ3MDNH7',
  );
}
